<?xml version="1.0" encoding="utf-8"?><Database Name="UltimateChangerDatabase" Class="DatabaseManagerDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=uchangerdb.database.windows.net;Initial Catalog=UltimateChangerDatabase;Persist Security Info=True;User ID=uchanger_admin" SettingsObjectName="Rekurencjon.Properties.Settings" SettingsPropertyName="UltimateChangerDatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Builds" Member="Builds">
    <Type Name="Build">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Release" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Mode" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="About" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Oem" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="BuildID" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Path" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>